language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry composer require satooshi/php-coveralls

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls -v